spring:
  datasource:
    url: jdbc:h2:file:./data;INIT=CREATE SCHEMA IF NOT EXISTS PERSON;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
